### PR TITLE
Update manual configuration

### PR DESCRIPTION
**Pull request by Rasbats**
Uses a common standard for the structure of the manual.

### CODE REVIEW

**Comment by Rasbats** [comment]
Thanks Steve. 
Provisional plugins manual with "Edit this page" is here: [https://opencpn-manuals.github.io/plugins](https://opencpn-manuals.github.io/plugins)
When you have time could you look at EngineDashboard and Racing. PR from Alec and Mike.

**Comment by TwoCanPlugIn** [comment]
Hi Mike,

I've accepted the PR's  for the Engine & Racing plugins.

Anything I need to do afterwards ?

I'm guessing  (hoping) no need to force a commit and an appveyor/circleci build cycle ?

Regards.

________________________________

**Comment by Rasbats** [comment]
Good stuff. Thanks.

No need for anything else. It would be nice to make a PR without those failing appveyor etc checks but I don't think this is possible at the moment.

Mike

**Comment by TwoCanPlugIn** [comment]
Hi Mike,

No probs.

I don't have any intentions of updating the Engine Dashboard, so I shan't worry about the entirely broken build process.

While I can understand the benefits for users with the plugin manager, and the overall benefit of the automated build process, to me I find it very complex and it just adds another layer of skills I need to master. I think I find I spend 5% of my time adding features, 40% testing and the remaining time fixing/understanding the build/tool chain.

Do you know if there is any updated documentation for building OpenCPN itself. Following the old developer manual, leads to a whole lot of compiler warnings and unresolved link warnings.

Cheers.



________________________________

**Comment by Rasbats** [comment]
Sorry ... I don't see the PR for Racing has been accepted!!!

Alec and Rick have been making a new development manual. Not yet published but ...
[https://opencpn-manuals.github.io/main/ocpn-dev-manual/5.3.1/od-compile-linux.html](https://opencpn-manuals.github.io/main/ocpn-dev-manual/5.3.1/od-compile-linux.html)

**Comment by TwoCanPlugIn** [comment]
My mistake, I thought I had, but clearly not.

Quite amazing all the integration between github & appveyor. It complained that the build was broken (no surprise).

I'll get around to fixing that as I was thinking of adding another feature or two.

Anyway all merged now.

________________________________

**Pull request merged**
