### PR TITLE
Simplify, cmake, cmakelists.txt, version, drivers, sample

### PR DESCRIPTION
**Pull request by rgleason**

### CODE REVIEW

**Review by TwoCanPlugIn — APPROVED** [review]

**Comment by TwoCanPlugIn** [comment]
Change Windows TwoCan plugin driver location to 'twocan_pi/data/drivers' as agreed.
Question: I assume this change is being made so appveyor/nsis can create a Windows installation package. What does it do in the case of a non-Windows build (Linux) ? Linux builds do not have any TwoCan plugin drivers and do not need a twocan_pi/data/drivers (not twocan_pi/data) directory.

Copy sample files to twocan_pi/data/sample as agreed, however will have to document that users will have to copy sample files to "My Documents" because if they choose to log their own data, the only location we can assume they have read/write access is "My Documents".

Question,: Similar to previous, What happens for Linux users ? Again only place that we can assume they have read/write access is their home folder. They would require sudo to be able to read/write log files to the /usr/libs (or whatever it is) directory.

If we are implementing the change to the plugin drivers directory to twocan_pi/data/drivers, I would be much happier if we didn't include copying of sample logs, and just left the location for log files as "My Documents" for Windows users and "Home" for Linux users, and merely document that if users want to test with sample logs then to download them manually  to the respective folders. I am a little concerned that playing with the log file locations will affect both Windows & Linux builds and installation packages.

**Comment by rgleason** [comment]
> Question: I assume this change is being made so appveyor/nsis can create a Windows installation package. 
- Yes.

> What does it do in the case of a non-Windows build (Linux) ? Linux builds do not have any TwoCan plugin drivers and do not need a twocan_pi/data/drivers (not twocan_pi/data) directory.
- Well, since linux does not need the dlls, I believe they just are not used. They might be sitting there in the repository, but they are not used in the build.

> Copy sample files to twocan_pi/data/sample as agreed, however will have to document that users will have to copy sample files to "My Documents" because if they choose to log their own data, the only location we can assume they have read/write access is "My Documents".
- I have to check, but I think this is happening right now due to your code. I have lots of log files being made in my My Documents directory, anyway.  If you need these files in My Documents, isnt there a way to have the plugin during initialization, copy these log files into My Documents?  Or have a button that would do that??

>Question,: Similar to previous, What happens for Linux users ? Again only place that we can assume they have read/write access is their home folder. They would require sudo to be able to read/write log files to the /usr/libs (or whatever it is) directory.
- Well, I think the answer is the same.  We have Weatherfax and Weather_routing and many others that copy files that need to be writeable to the appropriate plugin directory under 

ProgramData/opencpn/plugins/[pluginname]/data/ etc.
That is for windows. Linux has another location, somewhere under home/[user] I think.

If we are implementing the change to the plugin drivers directory to twocan_pi/data/drivers, I would be much happier if we didn't include copying of sample logs, and just left the location for log files as "My Documents" for Windows users and "Home" for Linux users, and merely document that if users want to test with sample logs then to download them manually to the respective folders. I am a little concerned that playing with the log file locations will affect both Windows & Linux builds and installation packages.

Yes, We can do that. You don't want to copy them to a writable location when the plugin initializes? Where would you download from?  Directions can be put in the manual.

While we are talking about these changes. Is it possible to compile all the dll's at the same time as the twocan plugin is compiled?   It would require some additional cmake commands I think, but that would be much better, because then we would not have binary files in a git code area, we would just have the code.  Then appveyor would compile it all and then copy the freshly made dlls to the data/drivers directory.  Then NSIS command would package it all.  My skills are not that good in this area, but maybe your knowledge will help.   (PS: I was considering downloading a 7z file of dlls and extracting it as an alternative, but finding a place to store that package was difficult. I do have a sourceforge account but have not really used it.

**Comment by TwoCanPlugIn** [comment]
Hi Rick,

I agree that having a single Windows installer for both the TwoCan plugin and the plugin drivers makes sense. My problem is that while I could add the plugin driver source (essentially merge the TwoCanPlugin and TwoCanPluginDrivers source), I don't yet have enough knowledge of cmake to build this. I guess thinking about it I need to add the following to the TwoCanPlugin/build/cmakelists.txt file

IF(WIN32)
 ADD_SUBDIRECTORY(Common)
 ADD_SUBDIRECTORY(Axiomtek)
 ADD_SUBDIRECTORY(Cantact)
 ADD_SUBDIRECTORY(FileDevice)
 ADD_SUBDIRECTORY(Kvaser)
 ADD_SUBDIRECTORY(CandumpLog)
 ADD_SUBDIRECTORY(KeesLog)
 ADD_SUBDIRECTORY(YachtDevicesLog)
ENDIF(WIN32)

Making sure the directory paths match up.

If I get a chance I'll try and test this (it would also solve on minor problem, in that I could now use a single twocanerror.h file rather than synchronize two (one for the plugin and another for the plugin drivers)

I think the sample data we're making too difficult. I think the ideal solution is to have a checkbox option in the installer (eg. Install Sample Logs) which will copy the sample logs into either "My Documents" for Windows users or "Home" for Linux users. Again, ;ile cmake, I have bugger all knowledge of NSIS !

BTW, Re your question what CAN adapter to buy, I think the Canable (especially the Pro version which has galvanic isolation and slightly better mounting; the normal version has no isolation or mounting holes !) would be a simple inexpensive choice. Connects via USB, works with both Windows & Linux (although I still have to add the write function for the Windows plugin driver in order to support Active Mode). And it seems to work very nicely with a Raspberry Pi as well.

Regards.

________________________________

**Comment by rgleason** [comment]
Steve,
Good ideas and suggestions, I think I'll try your suggestion locally for compiling.
Regarding sample logs, I wonder if there is a way to have a checkbox in Preferences "Install sample log files in the home or my documents directory"?

**Pull request merged**
